"""create employer and requirement tables

Revision ID: f3492302e967
Revises: 
Create Date: 2026-08-20 12:06:37.348755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3492302e967'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('organization_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_id'), 'employers', ['id'], unique=False)
    op.create_table('employer_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('requirement', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('qualification', sa.String(length=500), nullable=False),
    sa.Column('experience', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('required_within', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('target_date', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_requirements_id'), 'employer_requirements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employer_requirements_id'), table_name='employer_requirements')
    op.drop_table('employer_requirements')
    op.drop_index(op.f('ix_employers_id'), table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###
